### PR TITLE
more careful error checking running gpg

### PR DESCRIPTION
**Pull request by joshrabinowitz**
for #202, " Silence error on secret hide when GPG key expires"

Checks return codes of invocations of gpg

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
@sobolevn @simbo1905 you cool with me merging?

**Comment by joshrabinowitz** [comment]
@simbo1905 is this PR in the 0.2.4 release?

**Comment by simbo1905** [comment]
Until then - no fix merges. Can some else take a look at making travis only deploy from tags as I need to focus on some other things at the moment.

**Comment by joshrabinowitz** [comment]
* Well the good new is that all the versions of 0.2.4 should interoperate well (newer PRs have only changes for bats->bats-core, error messaging, and docs.)

* I agree, releases should not happen on 'merge to master' but instead when we tag the code.

* Yes, let's do a 2.5.0 tag/release when convenient.

**Comment by joshrabinowitz** [comment]
Also we should re-open #202 until the fix is released. Doing so now.

**Pull request merged**
