### PR TITLE
bump version to 0.2.5

### PR DESCRIPTION
**Pull request by joshrabinowitz**
In preparation for 0.2.5 release. @sobolevn @simbo1905 
For #236

### CODE REVIEW

**Comment by sobolevn** [comment]
@joshrabinowitz we also need to merge development into `master` after this commit.

**Comment by joshrabinowitz** [comment]
@sobolevn shall we merge this and release 0.2.5?

**Comment by sobolevn** [comment]
I think so! 🎉 

Great work!
I will tag it as `v0.2.5` after succefully merging this PR.

**Comment by joshrabinowitz** [comment]
oh- hope I didn't merge this too soon!

**Comment by sobolevn** [comment]
We can always release `0.2.6` 😄 

Thanks again to the awesome team of maintainers! @joshrabinowitz @hurricanehrndz @simbo1905

**Comment by sobolevn** [comment]
Taged and pushed: https://github.com/sobolevn/git-secret/releases/tag/0.2.5

**Pull request merged**
