### PR TITLE
fix changes command, consider only .secret files

### LINKED ISSUE #153: 'git secret changes' does not work unless passed secret filenames
Contrary to the docs, `git secret changes` does not work unless you pass it filenames of *.secret files.

In all cases with a git-secret repo, if you type

    `git secret changes`

You get no errors, but output like: 

````
     % git secret changes
    changes in /full/path/config.ini:
    <blank line>
````

For the command to work it must be passed the secret filenames (config.ini.secret).

### PR DESCRIPTION
**Pull request by joshrabinowitz**
Closes #153 

@sobolevn  -- Input requested 

Motivation: 'git secret changes' in 0.2.3 operated only on hidden .secret files

This PR alters the `changes` command to (by default, see below) work only on .secret files, and only reports if your local copies of the .secret files in your mapping file have changed or not from what's in your repo.

This is more in line with how the command actually operated so far. I'll update the tests to match the code once we decide how this command should actually operate.

I looked into adding a `git secret changes -c` option that would compare the decrypted versions of the hidden files to the decrypted version of what's in the repo, but am thinking it's not a great feature for these reasons:
* it requires the hidden files to be revealed and written to the filesystem, even if they were removed with (say) 'git secret hide -d'
* I'd think git-secret should consider the decrypted contents of files to be 'binary blobs' 

Here is output from 0.2.3:
````
% git secret changes
changes in /full/path/config.ini:

changes in /full/path/config2.ini:

changes in /full/path/config3.ini:
--- /dev/fd/63	2018-04-18 13:23:12.117609731 -0400
+++ /home/joshr/gitsrc/jcreds-amazon/config3.ini	2018-04-18 13:23:11.244612371 -0400
@@ -1 +0,0 @@
-
````

Here's output from this PR:

````
% git secret changes
config.ini.secret: changed
config2.ini.secret: changed
config3.ini.secret: no change
````

For a -c option as in `git secret changes -c`, I worked up a change that shows output like this, let me know if you like it and I'll commit it:

````
% git-secret changes   -c
config.ini.secret: changed
--- /dev/fd/63	2018-04-18 13:08:19.592297043 -0400
+++ /full/path/config.ini	2018-04-18 12:57:11.059297173 -0400
@@ -1,4 +1,4 @@
 foobar:
     access_key: YOO
     secret_access_key: HERE
-    dummy: 1
+    dummy: 2
config2.ini.secret: changed
 (no diff in /home/joshr/gitsrc/jcreds-amazon/config2.ini)
config3.ini.secret: no change
````

If these direction(s) are off-base then let's discuss how `git secret changes` _should_ work.

### CODE REVIEW

**Comment by sobolevn** [comment]
@joshrabinowitz thanks for the suggestion! And the implementation. It is nice and clean.

But, could you please explain your motivation in making 

```
% git secret changes
config.ini.secret: changed
config2.ini.secret: changed
config3.ini.secret: no change
```

a default behavior? 

For me, it does not give enough information. Because I will want to know what *did* change and how. I, personally, don't see any use-cases in this feature at all.
And, moreover, we will have to support two different outputs.

I think that it should work as follows:

```
$ git secret changes

changes in /full/path/config.ini:
--- before1
+++ after1

changes in /full/path/config2.ini:
--- before2
+++ after2

changes in /full/path/config3.ini:
--- before3
+++ after3
```

and for some files only:

```
$ git secret changes  /full/path/config.ini  /full/path/config2.ini

changes in /full/path/config.ini:
--- before1
+++ after1

changes in /full/path/config2.ini:
--- before2
+++ after2
```

**Comment by sobolevn** [comment]
But, while writing this I got an idea. We can create a special flag that would do the following:

```
$ git secret changes -s
# => returns 0 as exit code

$ ./modify_secrets
$ git secret changes -s
# => returns 1 as exit code
```

This feature can be useful during CI step.

**Comment by joshrabinowitz** [comment]
ok, follow, thanks.

**Comment by joshrabinowitz** [comment]
>could you please explain your motivation in making
>
>  % git secret changes
>  config.ini.secret: changed
>  config2.ini.secret: no change
> the default behavior?

Well, the basic thinking is that git-secret shouldn't make any assumptions about the contents of the encrypted files.  But I hear what you're saying.

**Comment by joshrabinowitz** [comment]
closed without merging. Replaced by PR #160

**Pull request closed without merging**
