### PR TITLE
make "usage" message easier to read

### PR DESCRIPTION
**Pull request by eliroca**
What does this implement/fix? 
---------------------------------------------------
this PR makes the output message of `git secret usage` easier to read:

Second try:
```
usage: git secret [--version] [command] [command-options]

options:
 --version                 - prints the version number

commands:
see 'git secret [command] -h' for more info about commands and their options
 add [file.txt]            - adds file to be hidden to the list
 cat [file.txt]            - decrypts and prints contents of the file
 changes [file.txt.secret] - indicates if the file changed since last commit
 clean                     - deletes all encrypted files
 hide                      - encrypts (or re-encrypts) the files to be hidden
 init                      - initializes the  git-secret repository
 killperson [emails]       - deletes a person's public key from the keyring
 list                      - prints all the added files
 remove [files]            - removes files from the list of hidden files
 reveal                    - decrypts all hidden files
 tell [email]              - imports a person's public key into the keyring
 usage                     - prints this message
 whoknows                  - prints list of authorized email addresses
```

Outdated - first try:
```
usage: git secret [--version] [add|cat|changes|clean|hide|init|killperson|list|remove|reveal|tell|usage|whoknows]

options:
 --version                 - will show version and exit

commands:
see 'git secret [command] -h' for more info about commands and their options
 add [filename.txt]        - adds file to be hidden, optionally adds file to .gitignore
 cat [filename.txt]        - cats the decrypted contents of the named file to stdout
 changes [filename.secret] - indicates if the file changed since last commit
 clean                     - deletes encrypted files
 hide                      - encrypts (or re-encrypts) the files to be hidden
 init                      - creates the .gitsecret directory and contents needed for git-secret
 killperson [emails]       - the reverse of 'tell', removes access for the named user
 list                      - shows files to be hidden/encrypted, as in .gitsecret/paths/mapping.cfg
 remove [files]            - removes files from list of hidden files
 reveal                    - decrypts all hidden files, as mentioned in 'git secret list'
 tell [email]              - add access for the user with imported public key with email
 usage                     - prints this message
 whoknows                  - shows list of email addresses associated with public keys that can reveal files
```

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
@eliroca thank you for this!

I like this PR, but worry that many people will be using the default 80 character wide terminal, and this will cause more output to wrap, causing the output to actually be less readable. Do you think you can shorten the descriptions so they fit on 80 character screens while keeping clarity?

**Comment by eliroca** [comment]
@joshrabinowitz I hope I've left the info clear enough. But it sure will make anyone using 80 char terminal happy :)

**Review by sobolevn — APPROVED** [review]
I like this a lot! Thanks!

**Comment by joshrabinowitz** [comment]
Yes this is great. Thank you again @eliroca

**Pull request merged**
