### PR TITLE
Update installation instructions to say that Cygwin is now supported

### PR DESCRIPTION
**Pull request by isen-ng**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Add `Cygwin` to the list of supported platforms. 
Blocked by https://github.com/sobolevn/git-secret/pull/601

Does this close any currently open issues?
------------------------------------------
NA

Any relevant logs, error output, etc?
-------------------------------------
NA

Any other comments?
-------------------
Should I link the ticket https://github.com/sobolevn/git-secret/pull/601 in the documentation?
I am asking because there is currently no CI machine setup to verify Cygwin. It's just manual testimony that it works for me.

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
@isen-ng , before I merge this, can you please confirm that `git-secret` passes self-tests using `make test`  on cygwin?

**Comment by isen-ng** [comment]
HMMMM. There wasn't any test failures when i ran it a long time before but there are 6 failures now.

For these, I'm sure it works. 
```
 ✗ run 'init' without '.git'
   (in test file /home/Isen/code/git-secret/tests/test_init.bats, line 27)
     `[ "$status" -eq 1 ]' failed

 ✗ run 'usage' without '.git'
   (in test file /home/Isen/code/git-secret/tests/test_usage.bats, line 28)
     `[ "$status" -eq 1 ]' failed

```

I've tested that it works when I run the commands manually
```
Isen@LAPTOP-JTKP23BL ~/code
$ ls -la
total 28
drwxr-xr-x+ 1 Isen None 0 Aug  4 13:31 .
drwxr-xr-x+ 1 Isen None 0 Sep 21 12:38 ..
drwxr-xr-x+ 1 Isen None 0 Sep 22 11:39 git-secret
drwxr-xr-x+ 1 Isen None 0 Jul 16 17:20 helm
drwxr-xr-x+ 1 Isen None 0 Sep  8 09:40 Java
drwxr-xr-x+ 1 Isen None 0 Aug  4 13:31 js
drwxr-xr-x+ 1 Isen None 0 Sep 10 10:30 python
drwxr-xr-x+ 1 Isen None 0 Jul 28 09:52 ruby

Isen@LAPTOP-JTKP23BL ~/code
$ git secret init
git-secret: abort: not in dir with git repo. Use 'git init' or 'git clone', then in repo use 'git secret init'

Isen@LAPTOP-JTKP23BL ~/code
$ echo $?
1

Isen@LAPTOP-JTKP23BL ~/code
$ git secret usage
git-secret: abort: not in dir with git repo. Use 'git init' or 'git clone', then in repo use 'git secret init'

Isen@LAPTOP-JTKP23BL ~/code
$ echo $?
1
```

for these, i suspect that it's because I have a key in my key ring that is not password protected?
so decryption is successful (but i assume the output is gibberish). For this, I'm not sure how to verify at the moment.

```
 ✗ run 'reveal' with wrong password
   (in test file /home/Isen/code/git-secret/tests/test_reveal.bats, line 109)
     `[ "$status" -eq 2 ]' failed

 ✗ run 'reveal' for attacker with -F (force)
   (in test file /home/Isen/code/git-secret/tests/test_reveal.bats, line 145)
     `[ ! -f "$FILE_TO_HIDE" ]' failed

 ✗ run 'reveal' with SECRETS_PINENTRY=error
   (in test file /home/Isen/code/git-secret/tests/test_reveal.bats, line 211)
     `[ "$status" -ne 0 ]' failed

**Comment by joshrabinowitz** [comment]
@isen-ng the errrors you're seeing running `git-secret init` in `~/code` are because you need to run in a directory with a `.git` subdirectory in it (that's what `not in dir with git repo` is complaining about).
I think you're meaning to test from a directory with checked out code.

Also if you are getting failing tests from `git-secret` on cygwin, can you please post the output of the failing tests from in the git-secret source directory (on the master branch) using
`SECRETS_TEST_VERBOSE=1 make test`

**Comment by joshrabinowitz** [comment]
@isen-ng I've merged the PR documenting that we now support cygwin.

If you could verify that git-secret does (or doesn't) work for you in Cygwin we would appreciate it! If it gives you issues please let us know what fails and which self-tests fail (with SECRETS_TEST_VERBOSE=1 output too please!)

Thanks again

**Pull request merged**
