### PR TITLE
sops support for encryption

### PR DESCRIPTION
**Pull request by learsix**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR implements sops as an alternative to gpg for file encryption / decryption.

Does this close any currently open issues?
------------------------------------------
Related issue #412 

Any relevant logs, error output, etc?
-------------------------------------
N/A

Any other comments?
-------------------
* All command options should be supported with `sops` (I mentioned in  #412 that some may not be supported for sops, e.g. `-p`).
* tests should probably be enhanced for sops. Group decryption and keyservice usage are not covered yet
* in main.sh, we detect whether the script is called as git-secret or as gpg command wrapper for sops. This is not clean (as it depends on gpg params passed by sops), I would suggest to use softlinks to sops script instead and detect how the script is used base on `$0`

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
It looks like this is failing (at least in part) because sops is not installed on the travis test VMs. 

Perhaps add code to clone and install sops for the travis environments? 
Let me know if you'd like me to give it a try (can't guarantee I'll get to it).

**Comment by joshrabinowitz** [comment]
@learsix I was looking at the code and realized that the tests seem to be using fd 3 for two purposes: 

 - bats-core outputs to fd 3 for 'diagnostic' messages
 - it looks like the new `_gpg_sops_wrapper_encrypt` uses fd 3 to for the passphrase.

**Comment by learsix** [comment]
@joshrabinowitz CI did indeed failed because sops was not installed : tests should be skipped if sops is not installed. I'm correcting this. Then I'll figure out how to add sops with travis ; I think we need to make sure that git-secret still works with gpg only and add sops as an option.
You're right about fd 3, I'm not sure that it impacts tests (`make test` is working locally for me). I'll look into it.

**Comment by learsix** [comment]
@joshrabinowitz fd3 will not impact tests. Using sops, git-secret forks to launch sops and sops forks to launch gpg wrapper (ie. git-secret / _gpg_sops_wrapper_encrypt). At this stage even if fd3 is inherited we overwrite it with a new fd.

**Comment by learsix** [comment]
Last commit should pass CI tests - without sops. Next thing to do is adding sops in CI env to actually test it.

**Comment by joshrabinowitz** [comment]
@learsix are you happy with this PR as it stands?

**Comment by joshrabinowitz** [comment]
@learsix I'm going to close this PR so it's not floating around being open. Feel free to re-open it and continue development if you get the urge! Thank you.

**Comment by learsix** [comment]
@joshrabinowitz Sorry I've been too busy in the past few weeks to finish this. I've started to test my fork in the field. They are still a few updates / tests to add. I'll let you know when it's done.

**Pull request closed without merging**
