### PR TITLE
add integration tests for alpine linux

### PR DESCRIPTION
**Pull request by nictrix**
What does this implement/fix? Explain your changes.
---------------------------------------------------
adds integration tests for alpine linux

Does this close any currently open issues?
------------------------------------------
should help wrap up the 0.2.3 release (https://github.com/sobolevn/git-secret/issues/98)
fixes: https://github.com/sobolevn/git-secret/issues/75

Any relevant logs, error output, etc?
-------------------------------------
Even before doing any changes, I got this failure on all test kitchen nodes:
```sh
         1) git-secret::test File "/.git-secret_lint-passed" should exist
            Failure/Error: it { should exist }
              expected File "/.git-secret_lint-passed" to exist
              env PATH="/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin" /bin/sh -c test\ -e\ /.git-secret_lint-passed
              
            # ./roles/git-secret/.ci-tests/integration/gnupg-git/serverspec/default_spec.rb:28:in `block (3 levels) in <top (required)>'
```

Any other comments?
-------------------
Please take a look at the Dockerfile for ci tests, I ended having to do a couple builds for dependencies and took all the test and build packages from ansible vars and put it there. Let me know your thoughts.

I didn't know what these files were for: `.docker/*` - but I put an alpine under the make directory.

### CODE REVIEW

**Comment by sobolevn** [comment]
@nictrix you made a great job! Thank you very much!

@hurricanehrndz could you please help me with the code review?

**Comment by hurricanehrndz** [comment]
@sobolevn, I will look at it this weekend.

**Comment by nictrix** [comment]
No problem, also that failure I mentioned - I ran shellcheck and found it. Should be fixed now.

**Comment by hurricanehrndz** [comment]
@nictrix  Thanks, not sure how that one lint check failure sneaked in.

**Comment by sobolevn** [comment]
Considering `.docker` folder. It is used to generate prebuilt containers for the DockerHub.

**Comment by hurricanehrndz** [comment]
@sobolevn ???

**Comment by sobolevn** [comment]
Oh, it *was* used.

**Comment by hurricanehrndz** [comment]
Does it make sense to distribute docker images of this program, it is a bash script after all? Seems like a of wasted space for such a small program. I don't think there is anything to be gain.

**Comment by hurricanehrndz** [comment]
There is a couple issues with this code, since I hadn't pushed upstream the most recent changes, but I will try and merge and rebase the code.

**Comment by nictrix** [comment]
Okay sounds good, I see you want to remove the .docker folder so I'll remove it from this PR also.

**Comment by hurricanehrndz** [comment]
This right here is the most recent code base, I haven't merged it into develop since I'm still doing some tweaks and tests.
https://github.com/sobolevn/git-secret/compare/develop...hurricanehrndz:awkinplace

**Comment by nictrix** [comment]
@hurricanehrndz okay sounds good - looks like you have alpine in there too, so whatever you want to do with this PR is fine by me (learned a lot from doing it), just figured from the 0.2.3 milestone it might have been needed.

And do let me know, close the PR, rebase, etc...

**Comment by hurricanehrndz** [comment]
@nictrix,

There is a lot in your PR that I think will be of good use. I will definitely try and merge it all this weekend. Thank you so much for your contributions. I only had the tests for alpine, I didn't have the build or Alpine package which will be super handy to have. We can definitely make use of all the help. How do you like doing documentation so that we can proceed forward with the release of 2.3?

**Comment by hurricanehrndz** [comment]
@nictrix,

Once I'm done with the merge, perhaps  we can talk about what's left and we can try and tackle it together.

**Comment by nictrix** [comment]
Sure sounds good, I can help with docs too. Is this repo on https://gitter.im ? or some other chat system...

**Comment by sobolevn** [comment]
@nictrix now it is! https://gitter.im/sobolevn/git-secret

**Comment by hurricanehrndz** [comment]
@nictrix,

I dropped the alpine git test. It didn't make sense to keep, since you built it with gcc, please remember muslc is the standard library for alpine. For now the latest alpine release will be tested against gnupgv1 and the gnpugv2 in the alpine repos.

**Pull request merged**
