### PR TITLE
Remove extra newline on changes

### LINKED ISSUE #291: git-secret-changes use of echo adds a newline
What are the steps to reproduce this issue?
-------------------------------------------
1. don't change FILE.pem.secret
2. run git-secret changes FILE.pem.secret

What happens?
-------------
`git-secret changes` shows that a newline at the end of the file was removed
```
--- /dev/fd/63	2018-12-28 08:43:13.000000000 -0800
+++ FILE.pem	2018-12-27 17:37:37.000000000 -0800
@@ -20,4 +20,4 @@
ASDFASDFASDFADFSADFSAFSDASDF...elided...
+-----END RSA PRIVATE KEY-----
\ No newline at end of file
```

What were you expecting to happen?
----------------------------------
no changes

Any logs, error output, etc?
----------------------------

```
    diff_result=$(diff -u <(echo "$decrypted") "$path") || true
```

Should instead be

```
    diff_result=$(diff -u <(echo -n "$decrypted") "$path") || true
```

What versions of software are you using?
----------------------------------------
0.2.4

### PR DESCRIPTION
**Pull request by BrandonCsSanders**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Fixes #291

Does this close any currently open issues?
------------------------------------------
#291

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
@BrandonCsSanders can you please re-create this branch based on the master branch? 
The docs in 2.4 aren't up-to-date, new branches should be cut from master. 
(The current docs say this: https://github.com/sobolevn/git-secret/blob/master/CONTRIBUTING.md#branches )

**Comment by joshrabinowitz** [comment]
Also there are some shellcheck errors shown at (ie) https://travis-ci.org/sobolevn/git-secret/jobs/473071000#L2253

**Comment by BrandonCsSanders** [comment]
> @BrandonCsSanders can you please re-create this branch based on the master branch?
> The docs in 2.4 aren't up-to-date, new branches should be cut from master.
> (The current docs say this: https://github.com/sobolevn/git-secret/blob/master/CONTRIBUTING.md#branches )

done

**Comment by joshrabinowitz** [comment]
I'm not sure this is an issue in git-secret master. 
Can you confirm it is still an issue with a self-test in master? 
I didn't spend a whole lot of time on it but I couldn't reproduce the underlying issue: See PR #293

**Comment by joshrabinowitz** [comment]
I figured out the issue, it is explained in #291

**Comment by joshrabinowitz** [comment]
Closing this PR as this issue is fixed in #293 
Thank you so much for bringing this to our attention, and submitting this PR, @BrandonCsSanders

**Pull request closed without merging**
