### PR TITLE
Fix gendered language

### PR DESCRIPTION
**Pull request by Haroenv**
What does this implement/fix? Explain your changes.
---------------------------------------------------
the person encrypting isn't necessarily male, so *their* works better in this case IMO

Does this close any currently open issues?
------------------------------------------
no

### CODE REVIEW

**Comment by sobolevn** [comment]
Sorry, I don't get it.

**Comment by Haroenv** [comment]
I changed "him" to "their" so it isn't exclusively male :smile:

**Comment by sobolevn** [comment]
So, ok, I guess...

Could you please rebase your PR to the `develop` branch?

**Comment by Haroenv** [comment]
Sure

**Pull request merged**
