### PR TITLE
describe Windows installation

### PR DESCRIPTION
**Pull request by bennycode**
Adding details for Windows users to: https://git-secret.io/installation

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
This is fine by me, because I have no idea about how windows works.

**Comment by bennycode** [comment]
I just reinstalled Windows 11 and `git-secret` on my PC, so I had to go through these steps and thought it would be nice to add them to the official docs. :)

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
I will let @joshrabinowitz to merge this, maybe provide some extra feedback 🙂

**Comment by joshrabinowitz** [comment]
Can we add mention alternatives like wsl, cygwin, and mingw-w64? If the docs could explain the differences a little bit too, and why someone would choose one or another path, that would be great. It seems like there's a bunch of ways to go to use git-secret on windows.

**Pull request merged**
