### PR TITLE
Develop

### LINKED ISSUE #6: Is there a compatibility issue with GnuPG 2.X ?
## Info

using zplug for adding git-secret

``` sh
gpg (GnuPG) 2.1.11
git version 2.7.3
```

Error message

``` sh
no users found. run 'git secret tell' before adding files. abort.
```

**Even though I had done that**
## Tests

``` sh
34 tests, 17 failures
```

P.S. do you need the full test detail?

### LINKED ISSUE #46: "make test" is failing for `gnupg2>=2.1.0`
I run "make test" and see error message "line 96: _get_gpg_fingerprint_by_email: command not found" . It prompts for passphrase on gpg key "user1@gitsecret.io" "user2@gitsecret.io"

Should I create gpg keys for user1 and user2? Could you mark about this in CONTRIBUTING.md ?

### LINKED ISSUE #92: Feature request: "git secret hide" should only touch modified files
It would be nice if `git secret hide` would only re-encrypt files if the underlying plaintext file has changed.

What are the steps to reproduce this issue?
-------------------------------------------
1. `git secret hide`
2. `git commit -am "save secrets"`
3. `git secret hide`
4. `git status`

What happens?
-------------
`git status` shows that git-secret-hide has rewritten all of my secret files, plus the random_seed file.

What were you expecting to happen?
----------------------------------
Ideally, the `git secret hide` in step 3 would have been a no-op since none of the underlying plaintext has changed.

What versions of software are you using?
----------------------------------------
**Operating system:** Mac OS X 10.11.6 (El Capitan)

**`git-secret` version:** 0.2.2

**Shell type and version:** zsh 5.0.8 (x86_64-apple-darwin15.0)

### LINKED ISSUE #99: Add more gpg versions to the test matrix
We need to test several `gpg` versions:

1. `gpg` version 1
2. `gpg` version 2
3. `gpg` latest release
4. `pgp` if available

### PR DESCRIPTION
**Pull request by hurricanehrndz**
What does this implement/fix? Explain your changes.
---------------------------------------------------
There are 3 major updates in this pull request which are as follows:
1. Wrote test-kitchen tests in order to more efficiently and dynamically test various version of gpg against more platforms. Thus, closing #99.
2. Added the ability for git-secret to keep track of sha256  hashes of the secret files in the path mappings file. Thus, re-encrypting secrets only on changes. Closing issue #92
3. Fix failing test introduced by merge request #103.
4. Fixed the fact that test did not run on modern gnupg versions (Exported the keys prior to running tests, enforced lookback pinentry on tests in order to be able to pipe passphrase). Closing #6.

Does this close any currently open issues?
------------------------------------------
Closes #99
Closes #92
Closes #46 
Closes #6 

Any relevant logs, error output, etc?
-------------------------------------
Ubuntu 16.04 kitchen ci test disabled as they failed because the gpg version included is unsupported. 

Any other comments?
-------------------
In order for CentOS to be supported, which it can with a lot of work, the _check_ignored function would need to be refactored. Additionally, gawk features (i.e inplace) would need be dropped and the code refactored. 

Travis ci test could be re-written to implement the test-kitchen written tests.

### CODE REVIEW

**Comment by sobolevn** [comment]
Just wow! You are officially awesome.

**Comment by sobolevn** [comment]
What `gawk` is used for?

That's how we'll do it if you don't mind: 
- I am merging this as is in `develop`
- I am giving you writing access to this repo
- We are testing it together

Sound good to you?

**Comment by hurricanehrndz** [comment]
@sobolevn,

There were some statements were awk scripts were just simpler to read and write than multiple grep and sed statements. Plus I believe there should be some performance gains. Additionally, it is a lot easier to manage the FSDB  (File System DataBase) which path mappings has become with awk, since it specifically deals with field separators. Path mappings is now formatted like so

```
file_path:sha256sum
``` 
When using the "-m" option with hide it will track the sha256sum of secrets and thus will only encrypt files if there hash has change.  There may be concerns about data leakage because of the sums, but I think the possibilities of finding a hash collision would be nearly impossible. 

Yes, please merge with develop. Test still need to be added for the "-m" option, but other than that, it has been pretty well documented. I believe the addition of test-kitchen as local ci will also help future contributors ensure there code is bug free before doing a pull request.

Your very welcome and thank you for the hard work you put in to such a great project.

Feedback is welcome on the placement of the AWK scripts, I believe it is the only part of the code that I'm not fully satisfied with. Maybe they should all be in a separate file that get source by the main _utils script.

**Comment by hurricanehrndz** [comment]
@sobolevn,

I think issue #105 will be fixed soon, just waiting on feedback by the original poster. I will need to refactor some of the awk scripts in order to abandoned features used that are not present in CentOS. Once that is complete and #105 checks out than CentOS should be supported, I will add it to the test framework.

**Comment by sobolevn** [comment]
@hurricanehrndz merged all the commits, did not squashed them, since I want to preserve history.

**Comment by sobolevn** [comment]
@hurricanehrndz made you a collaborator. Thank you for the hard work! I appreciate it.

**Comment by hurricanehrndz** [comment]
Thanks fro the merge, and making a collaborator. What are your plans going forward? Release cycle and such?

**Comment by sobolevn** [comment]
Created some issues.

**Comment by hurricanehrndz** [comment]
Sounds good.

**Pull request merged**
