### PR TITLE
use gpg --armor when hiding/encrypting files

### PR DESCRIPTION
**Pull request by joshrabinowitz**
For #631: 

Use gpg --armor when encrypting/hiding files, so secret files are text instead of binary.

When testing with gpg 2.0.22 and git-secret master,  I found that I could 'reveal' files encrypted whether or not they had been hidden with the --armor option.

This needs to be tested with older and newer versions of gpg

### CODE REVIEW

**Comment by jpbochi** [comment]
Hopefully, this won't be a breaking change, since `gpg` is able to decrypt files regardless of them being in binary or armored text formats.

I do like the idea of making armored text be the default format. The only advantage of binary is that the files would be smaller, but that's not a big difference for files that are typically small.

**Comment by joshrabinowitz** [comment]
I think this may fix #136

**Comment by joshrabinowitz** [comment]
@sobolevn Also I rebased master into this branch, but that might not be the right thing (itnow shows over 300 files changed). let me know if I should recreate this branch or something else

**Comment by sobolevn** [comment]
@joshrabinowitz yes, I think that you should create a new branch and cherry-pick the required commits from `joshrabinowitz:issue-630-hide-armored` into it! 👍

**Comment by joshrabinowitz** [comment]
See replacement PR #661

**Comment by joshrabinowitz** [comment]
This PR is replaced by #661

**Pull request closed without merging**
