### PR TITLE
Add cygwin support

### LINKED ISSUE #40: windows support
Right now `git-secret` does not support `windows` operating systems. But the architecture is suitable to handle it.

I have never actually worked with `windows`. And I have neither time nor will to get starting.

What are the limitations? 
What frameworks/external programs does it require to run `bash` on `windows`? 
Is it even possible?
How many tests do pass right now (if any)?

I would highly appreciate any help on this topic!

### PR DESCRIPTION
**Pull request by isen-ng**
What does this implement/fix? Explain your changes.
---------------------------------------------------
I have installed git secret using the manual steps in cygwin and the operations work.
This is the only change I had to make to make this work. Apparently, it already has been confirmed before but no PR was sent:
https://github.com/sobolevn/git-secret/issues/40#issuecomment-299239825

Does this close any currently open issues?
------------------------------------------
Fixes #40

Any relevant logs, error output, etc?
-------------------------------------
```
$ git secret init
git-secret: init created: '/home/Isen/code/my-project/.gitsecret/'

$ git secret tell isen.ng@my-email.com
gpg: keybox '/home/Isen/code/my-project/.gitsecret/keys/pubring.kbx' created
gpg: /home/Isen/code/my-project/.gitsecret/keys/trustdb.gpg: trustdb created
git-secret: done. isen.ng@my-email.com added as user(s) who know the secret.

$ git secret add my-secret.yml
git-secret: these files are not in .gitignore: my-secret.yml
git-secret: auto adding them to .gitignore
git-secret: 1 item(s) added.

$ git secret hide -m
git-secret: done. 1 of 1 files are hidden.
```

Any other comments?
-------------------
Not sure if there are anything else to change ...
* Do i need to add some windows tests on travis? or it seems that the tests are broken ATM.
* Do i need to update the documentation? 
  - https://git-secret.io/installation still says cygwin support is planned

### CODE REVIEW

**Comment by isen-ng** [comment]
Hmm, anything I can do to help fix the ci?
The ci failed with `The command "chmod +x ".ci/script.sh" && ".ci/script.sh"" exited with 2.`

**Comment by sobolevn** [comment]
Yes, for some reason we have a failing test:

```
               "not ok 74 run 'remove' for nameless user normally",

               "# (from function `set_state_secret_hide' in file /tmp/git-secret/tests/_test_base.bash, line 254,",

               "#  from function `setup' in test file /tmp/git-secret/tests/test_noname.bats, line 20)",

               "#   `set_state_secret_hide' failed with status 2",

               "#   PID TTY          TIME CMD",

               "#  2009 pts/0    00:00:00 sudo",

               "#  2010 pts/0    00:00:10 ansible-playboo",

               "# 16759 pts/0    00:00:00 ansible-playboo",

               "# 16774 pts/0    00:00:00 sh",

               "# 16775 pts/0    00:00:00 sh",

               "# 16776 pts/0    00:00:00 python",

               "# 16777 pts/0    00:00:00 make",

               "# 16789 pts/0    00:00:00 bash",

               "# 16792 pts/0    00:00:00 bash",

               "# 16796 pts/0    00:00:00 bash",

               "# 16797 pts/0    00:00:00 bash",

               "# 18944 pts/0    00:00:00 bash",

               "# 18945 pts/0    00:00:00 bash",

               "# 18952 pts/0    00:00:00 bash",

               "# 19490 pts/0    00:00:00 ps",
```

Related #602

**Comment by joshrabinowitz** [comment]
We need someone with bash skill and access to a cygwin setup to debug this and/or make a fix before we can merge.

**Comment by joshrabinowitz** [comment]
@isen-ng can you please look at the comment above 
and paste results of the same test after setting 
SECRETS_TEST_VERBOSE=1  and SECRETS_VERBOSE=1 in your environment?

**Comment by isen-ng** [comment]
Sure! I'll do it in the coming week

**Comment by isen-ng** [comment]
I've given it a few tries. It is still currently beyond me.
but it seems to me that this is not a cygwin/windows issue because the problem manifests on the linux and osx ci instances.

**Comment by joshrabinowitz** [comment]
@isen-ng oh hey, you're right. I'll take a look into in the next couple of days. Thanks for the info.

**Comment by joshrabinowitz** [comment]
The issue seems to be that one of the keys used in git-secret testing has expired. I plan to write up an issue about this and propose a fix soon.

**Comment by sobolevn** [comment]
@joshrabinowitz can we generate keys that won't expire? Or expire in 2100, so it won't be **our** problem? 😆

**Comment by joshrabinowitz** [comment]
@sobolevn the expired key issue (#608) has been fixed.

**Comment by joshrabinowitz** [comment]
@isen-ng , can you merge `master` into your branch and confirm that it makes all the tests pass? 

Then we'll merge this branch, and add a ticket to update (or just update) the page at https://git-secret.io/installation

**Comment by isen-ng** [comment]
@joshrabinowitz @sobolevn 

Rebased off updated master.
I will send a different PR to update the documentation

**Pull request merged**
