### PR TITLE
Support SECRETS_TELL_GPG_OPTIONS for key discovery

### PR DESCRIPTION
**Pull request by joshrabinowitz**
Allows user to specify options for gpg to find keys to import. 
For #509

### CODE REVIEW

**Comment by bricewge** [comment]
I tried following the asciinema again with this PR but I can't manage to get it working. I'm not sure if it come from the PR or another issue on my side. Following is the log:
``` shell 
$ git-secret tell -v -m
gpg: keybox '/home/bricewge/tmp/git-secret-test2/.gitsecret/keys/pubring.kbx' created
gpg: /home/bricewge/tmp/git-secret-test2/.gitsecret/keys/trustdb.gpg: trustdb created
/home/bricewge/tmp/git-secret/git-secret: line 1817: 3: Bad file descriptor
git-secret: cleaning up: /tmp/_git_secret.AMor4L
```

**Comment by joshrabinowitz** [comment]
@sobolevn what do you think about putting a key like `user6@gitsecret.io' (or whatever, but a test key) on hkps://keys.openpgp.org , specifically for an optional test that would let us test SECRETS_TELL_GPG_OPTIONS ? 

See #509 and https://github.com/sobolevn/git-secret/issues/491#issuecomment-505418594

**Comment by bricewge** [comment]
I have uploaded the public key of `user5@gitsecret.io`: https://keys.openpgp.org/search?q=F6D18D19A97F4C48A5DE7D926E519D838D21481F.

**Comment by joshrabinowitz** [comment]
Putting this on the back-burner for a while and closing this PR.

Kind reader, feel free to recreate and continue this branch.

**Pull request closed without merging**
