### PR TITLE
Automate the GitHub release

### PR DESCRIPTION
**Pull request by simbo1905**
What does this implement/fix? Explain your changes.
---------------------------------------------------

This adds a travis-ci deploy step that creates a draft github release. Note that a draft release that will only be visible to collaborators. You need to edit it and hit the publish button to make it a final public release. The script uses [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator) that creates a list of merged PRs, fixed bug and enhancements since the last release. You should check that that is accurate before publishing the release and if it isn't then manually edit it on github before publishing. At the point of publishing the draft release, there is a tickbox to mark it as a pre-release, I haven't tested it but it should be possible to do a `v1.0-M1` release and pubish it as a pre-release. 

Does this close any currently open issues?
------------------------------------------

#194 automate the GitHub release

Any other comments?
-------------------

The script needs an environment variable GITHUB_OAUTH_TOKEN set up on the travis build which was set up as per the discussion at https://github.com/sobolevn/git-secret/issues/194#issuecomment-397650107

I ran tested it on my own fork at https://www.travis-ci.org/simbo1905/git-secret/jobs/504198355 and it created a  release at https://github.com/simbo1905/git-secret/releases/tag/v0.2.15

The script uses curl to read the last release github api to extract the latest release number. It then computes the change log since that version. There could be a future scenario where we have two active major versions v1.x and v2.x in which case the logic to compute the latest release to compare against will not be good enough. As long as we only have a single version to compute the latest changes against things should work okay. 

When testing the script if I created and pushed a tag but had not first pushed the whole branch then it kicked off the builds but the deploy script failed with the following error message: 

```
Deploying application
Not currently on any branch.
```

I would expect we would always release from master were we had squash-merged all commits into it and seen a successful build before applying and pushing a tag. Things should work as expected when we do that so I don't think that we should see this error in practice.

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
Thanks @simbo1905 , I'll try to look at this in-depth this week.

**Comment by joshrabinowitz** [comment]
I took a run through, and it looks pretty straightforward.

I did have these questions

* Why are we replacing our hand-crafted CHANGELOG.md?

* Can we briefly document what jq is and what package it comes from (I looked it up, but it might be new to readers)?

* How about using long params when calling github_change_generator to increase self-documentation?

Seems like we should eventually add some of the text from the comments in #411 into the code base.

Also, re: >"There could be a future scenario where we have two active major versions v1.x and v2.x in which case the logic to compute the latest release to compare against will not be good enough" - I don't see that being an issue for a while.

re: >"if I created and pushed a tag but had not first pushed the whole branch then..."  we can just put a comment about this in the text.

Maybe also we should consider separating the CONTRIBUTING.md file into two parts, one for 'serious git-secret developers' and one for 'people wanting to quickly submit patches'.

**Comment by simbo1905** [comment]
> Why are we replacing our hand-crafted CHANGELOG.md?

It is using a tool [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator) to generate a changelog for the delta of the current git tag to the last release from github using all the data in GitHub. The script doesn't commit that file it just uploads it to the github release page. Nothing is committed it is just clobbering the local file. 

Should we be using a hand-crafted CHANGELOG.md when we have this feature? We will get a detailed change log for each new release that is automatically generated from GitHub so less work and won't be error prone. As we are using squash-merge of PRs as long as the PR titles are clear (and can be edited on the squash merge) we will get a very clean auto-generated changelog using this tool. 

Perhaps we can move the current "history of all changes changelog" into the body of the current release on GitHub. Then we can just add a changelog section to the readme that links to the github releases page. 

> Can we briefly document what jq is and what package it comes from (I looked it up, but it might be new to readers)?

A hyperlink to its project page? 

jq is great for shellscripts that need to parse JSON. there is another project yq that mimics it for YAML. 

> How about using long params when calling github_change_generator to increase self-documentation?
 
Sure why not.

**Comment by joshrabinowitz** [comment]
Hello @simbo1905 
> re: changelog / generated_log.txt

Yes for now I'd like to continue using CHANGELOG.md, I like the idea of a `generated_log.txt` too, but I'm not sure it necessary.   Also I don't always use ideal commit messages, so I'm not sure the autogenerated log will be very useful --  perhaps we should add docs or a link to how commit messages should be written.

Yes, a one-line description of jq and perhaps a link sounds good.

Once we merge this (and maybe the windows branch), and [you, me and @sobolevn] agree, how would you feel about performing a release of 0.3.0 as we talked about in #318 ?

**Comment by simbo1905** [comment]
I will check the comments on the suggestion of the new release. 

I also make many small commits with random comments :-) If we are using squash-merge of a PR the commit comment of the squashed work defaults to  the PR title and number, yet when you do the squash merge you have an opportunity edit it. So we should have good commits on master. 

Note the script doesn't change what is in the git repo. It uploads the generated release notes to the releases page on github which is not in the main repo but some other github storage that people can release zip or binary files. 

Finally the script is generating draft releases only contributors can see and that can be amend before publishing. So if one of the squash merge commits is not clear it should be possible to edit the generated release notes of the draft release. 

The key point being with automation it's less effort and less chance of missing something off the generated release note. 

I don't know how good the generated changelog will be. It has had over a thousand commits from 64 contributors so I am hopeful. Let's parallel run it with the current manual one. 

I will try to make the suggested changes this evening.

**Comment by joshrabinowitz** [comment]
>  If we are using squash-merge of a PR the commit comment of the squashed work defaults to the PR title and number...

Yes, that's pretty good in the absence of something better. I'm all for an autogenerated change history, I'm just not sure its data should be presented in place of our CHANGELOG.md -- see below.

>Note the script doesn't change what is in the git repo.

Yes, I saw that, that's cool.

I suspect that an autogenerated commit history, even squashed-merged by PR (which we're doing now pretty religiously), is still less informational that our handwritten `CHANGELOG.md`. `CHANGELOG.md` for example lists changes by the Issue they address, not the PR they were merged from. I could think of other reasons, but: I'm looking forward to being able to compare the output of the changelogs for now though

All this having been said, I'm appreciative this is moving along, stoked to be able to compare autogenerated and our current changelogs, and looking forward to seeing this get merged!

**Comment by joshrabinowitz** [comment]
I mean, have you seen how pretty our CHANGELOG.md is now?
https://github.com/sobolevn/git-secret/blob/master/CHANGELOG.md  ;)

**Comment by simbo1905** [comment]
I don't have time to manually check its accuracy! ;-p

**Comment by joshrabinowitz** [comment]
I'm not sure that's a great reason to _replace_ the CHANGELOG.md info. 

In any case I can vouch for the accuracy of the CHANGELOG.md records for this release.

**Comment by simbo1905** [comment]
My suggestion is to run it in parallel and see what it does. We can keep the manual history forever if you want. We may hate this new one its an experiment.

**Comment by simbo1905** [comment]
All checks have passed so if folks are okay I will squash merge this.

**Comment by joshrabinowitz** [comment]
Since we're not replacing CHANGELOG.md why don't we use github_changelog_generator's   
    `-o, --output [NAME]` 
option so we don't have to do the two-step mv shuffle with CHANGELOG.md shown below?

````
mv CHANGELOG.md CHANGELOG.md.bak
# Generate CHANGELOG.md
github_changelog_generator (...options elided...)
body="$(cat CHANGELOG.md)"
mv CHANGELOG.md.bak CHANGELOG.md 
````

**Comment by joshrabinowitz** [comment]
I'm good with merging this once the CHANGELOG.md `mv` two-step is resolved.

**Comment by joshrabinowitz** [comment]
And can we please add an appropriate entry for this (mentioning the Issue fixed) into our hand-generated CHANGELOG.md too?

**Comment by simbo1905** [comment]
I tried `--output` but the tool will use any manual changelog that is there. So i have simplified things to just `rm` the manual log.

**Comment by simbo1905** [comment]
There was a transient build on alpine that passed on a rebuild. This release logic is on fedora so unrelated.

**Comment by simbo1905** [comment]
Okay, I will merge this if everyone is okay. If we like this feature then the plan will be to rename our manually maintained file as HISTORY.md. The script will then append to that file. Meanwhile while we are parallel running this script it deletes the manual changelog else it is appended to what this script generates.

**Comment by joshrabinowitz** [comment]
@simbo1905 sounds good, let it rip!
If we don't love CHANGELOG.md / HISTORY.md then we can iterate.

**Pull request merged**
