### PR TITLE
New CI

### LINKED ISSUE #657: New CI
Here's my plan:
- Moving from `travis` to GitHub Actions, bacuse `travis` does not work anymore
- Removing `kitchen`, it is overly complex - I don't have any experience with it
- Removing `ansible`, it is used by `kitchen`
- Dropping `ruby` support, currently we use `ruby` for four reasons: `kitchen` (will be dropeped), `fpm` (can be replaced with native `deb` / `rpm` package builders), `ronn` (can be used in a separate job with `ruby` support), `jekyll` build for docs (in a separate build)

I am also going to simply test setup as much a I can.

Platforms to test:
- Debian
- Fedora / CentOS
- Alpine
- MacOS
- Windows? (I don't use it and have no idea how to work with it, so no promises here)

Matrix:
- We need an extra test for `gnupg1`

Releases:
- Currently it is not clear, where to release things, but attaching binary artifacts to GitHub releases seems like a good idea: see #646

### PR DESCRIPTION
**Pull request by sobolevn**
Closes #657
Refs #646

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
* is the .ronn file deletion intended?
* I notice the new man page files don't seem to include version numbers. intentional?
* will look at this more in the next few days

**Comment by sobolevn** [comment]
This is now ready to be reviewed! Releasing part is missing for now, because I first want to make sure that everything else is correct.

I understand that there are lots of changes, but I guess the final simplicity is worth the refactoring.

**Comment by sobolevn** [comment]
@joshrabinowitz 

> is the .ronn file deletion intended?

It is not synced from main `./man` folder into `docs`, see: https://github.com/sobolevn/git-secret/blob/issue-657/.github/workflows/github-pages.yml#L18

>  I notice the new man page files don't seem to include version numbers. intentional?

Sorry, I don't understand this one 😞 

> will look at this more in the next few days

Thanks a lot for your help! 👍

**Comment by sobolevn** [comment]
Wow, this was hard 😅

**Comment by joshrabinowitz** [comment]
re my comment: _I notice the new man page files don't seem to include version numbers._
I meant that the generated man pages (such as `man/man1/git-secret-whoknows.1`) no longer have the version of git-secret in the header; for example the output of  ` git diff master -- man/man1` `shows

-.TH "GIT\-SECRET\-ADD" "1" "April 2021" "sobolevn" "git-secret 0.3.3"
+.TH "GIT\-SECRET\-ADD" "1" "May 2021" "sobolevn" "git-secret "

**Comment by joshrabinowitz** [comment]
Looks good otherwise

**Comment by sobolevn** [comment]
Docs preview now works by `make docs`
Снимок экрана 2021-05-04 в 12 16 46

**Comment by sobolevn** [comment]
Ok, I am going to merge this one and start working on new releases. I already a big progress on `deb` releases, but it requires a lot more polishing.

Any comments are still welcome, I will implement them in async mode! 👍

**Pull request merged**
